using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WatiN.Core;

namespace InsuranceAppWebUI.CA
{
    public class CAPilotPage
    {
        private Browser browser;
        public CAPilotPage(Browser bro)
        {
            browser = bro;
        }

        public string txtPilotInfoName { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoName")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoName")).Value = value; } }
        public string hiddenPilotCountSub { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_hiddenPilotCountSub")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_hiddenPilotCountSub")).Value = value; } }
        public string txtPilotInfoNameLast { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoNameLast")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoNameLast")).Value = value; } }
        public string HiddenField1 { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_HiddenField1")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_HiddenField1")).Value = value; } }
        public string txtPilotInfoOccupation { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoOccupation")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoOccupation")).Value = value; } }
        public string txtPilotInfoAge { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoAge")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoAge")).Value = value; } }
        public string txtPilotInfoTotalHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoTotalHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoTotalHours")).Value = value; } }
        public string txtPilotInfoTotalHoursLast12Mths { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoTotalHoursLast12Mths")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPilotInfoTotalHoursLast12Mths")).Value = value; } }
        public string txtRGHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtRGHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtRGHours")).Value = value; } }
        public string txtMEHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtMEHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtMEHours")).Value = value; } }
        public string txtTWHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtTWHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtTWHours")).Value = value; } }
        public string txtSeaplaneHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtSeaplaneHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtSeaplaneHours")).Value = value; } }
        public string txtAmphibianHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtAmphibianHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtAmphibianHours")).Value = value; } }
        public string txtRWHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtRWHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtRWHours")).Value = value; } }
        public string txtSkiplaneHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtSkiplaneHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtSkiplaneHours")).Value = value; } }
        public string txtWSCTrikeHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtWSCTrikeHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtWSCTrikeHours")).Value = value; } }
        public string txtPPCHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPPCHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtPPCHours")).Value = value; } }
        public string txtGliderHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtGliderHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtGliderHours")).Value = value; } }
        public string txtGyroHours { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtGyroHours")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtGyroHours")).Value = value; } }
        public string txtAdditionalInfo { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtAdditionalInfo")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtAdditionalInfo")).Value = value; } }
        public string txtNoCurrentMedicalExplanation { get { return browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtNoCurrentMedicalExplanation")).Value; } set { browser.TextField(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_txtNoCurrentMedicalExplanation")).Value = value; } }
        public bool cbxPilotInfoRatings0 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_0")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_0")).Checked = value; } }
        public bool cbxPilotInfoRatings3 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_3")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_3")).Checked = value; } }
        public bool cbxPilotInfoRatings1 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_1")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_1")).Checked = value; } }
        public bool cbxPilotInfoRatings4 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_4")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_4")).Checked = value; } }
        public bool cbxPilotInfoRatings2 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_2")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoRatings_2")).Checked = value; } }
        public bool cbxPilotInfoViolations0 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_0")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_0")).Checked = value; } }
        public bool cbxPilotInfoViolations1 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_1")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_1")).Checked = value; } }
        public bool cbxPilotInfoViolations2 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_2")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_2")).Checked = value; } }
        public bool cbxPilotInfoViolations3 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_3")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_3")).Checked = value; } }
        public bool cbxPilotInfoViolations4 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_4")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxPilotInfoViolations_4")).Checked = value; } }
        public bool cbxAircracftCheck0 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxAircracftCheck_0")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxAircracftCheck_0")).Checked = value; } }
        public bool cbxAircracftCheck1 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxAircracftCheck_1")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxAircracftCheck_1")).Checked = value; } }
        public bool cbxAircracftCheck2 { get { return browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxAircracftCheck_2")).Checked; } set { browser.CheckBox(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_cbxAircracftCheck_2")).Checked = value; } }
        public SelectList ddlPilotInfoCertificate { get { return browser.SelectList(Find.ById("main_0_eaamain_0_eaacontent_0_acmain_1_Quote_xQuoteWizard_xPilot_ddlPilotInfoCertificate")); } }

    }
}
