//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAppWebUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public System.Guid ContentGUID { get; set; }
        public System.Guid AppGUID { get; set; }
        public string FilenameExt { get; set; }
        public string Filename { get; set; }
        public byte[] Content1 { get; set; }
        public Nullable<bool> Compressed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
