//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceAppWebUI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EAA_Memorial_WallEntities : DbContext
    {
        public EAA_Memorial_WallEntities()
            : base("name=EAA_Memorial_WallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GuestBook> GuestBooks { get; set; }
        public virtual DbSet<Obituary> Obituaries { get; set; }
    
        public virtual int spGuestBook_DelRecord(Nullable<int> guestBookID)
        {
            var guestBookIDParameter = guestBookID.HasValue ?
                new ObjectParameter("GuestBookID", guestBookID) :
                new ObjectParameter("GuestBookID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGuestBook_DelRecord", guestBookIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGuestBook_NewRecord(Nullable<int> obituaryID, Nullable<System.DateTime> dateSubmitted, string submitterName, string submitterMemberNum, string submitterComments, string approver, string approved, Nullable<System.DateTime> approvalDate, string approverComments, string signedByDBTeam4EAA, ObjectParameter retrunValue)
        {
            var obituaryIDParameter = obituaryID.HasValue ?
                new ObjectParameter("ObituaryID", obituaryID) :
                new ObjectParameter("ObituaryID", typeof(int));
    
            var dateSubmittedParameter = dateSubmitted.HasValue ?
                new ObjectParameter("DateSubmitted", dateSubmitted) :
                new ObjectParameter("DateSubmitted", typeof(System.DateTime));
    
            var submitterNameParameter = submitterName != null ?
                new ObjectParameter("SubmitterName", submitterName) :
                new ObjectParameter("SubmitterName", typeof(string));
    
            var submitterMemberNumParameter = submitterMemberNum != null ?
                new ObjectParameter("SubmitterMemberNum", submitterMemberNum) :
                new ObjectParameter("SubmitterMemberNum", typeof(string));
    
            var submitterCommentsParameter = submitterComments != null ?
                new ObjectParameter("SubmitterComments", submitterComments) :
                new ObjectParameter("SubmitterComments", typeof(string));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var approverCommentsParameter = approverComments != null ?
                new ObjectParameter("ApproverComments", approverComments) :
                new ObjectParameter("ApproverComments", typeof(string));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGuestBook_NewRecord", obituaryIDParameter, dateSubmittedParameter, submitterNameParameter, submitterMemberNumParameter, submitterCommentsParameter, approverParameter, approvedParameter, approvalDateParameter, approverCommentsParameter, signedByDBTeam4EAAParameter, retrunValue);
        }
    
        public virtual int spGuestBook_SearchReturns(string searchStr, string firstName, string lastName, string submitterName, string decFrom, string decTo, string keywords, string approved)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var submitterNameParameter = submitterName != null ?
                new ObjectParameter("SubmitterName", submitterName) :
                new ObjectParameter("SubmitterName", typeof(string));
    
            var decFromParameter = decFrom != null ?
                new ObjectParameter("decFrom", decFrom) :
                new ObjectParameter("decFrom", typeof(string));
    
            var decToParameter = decTo != null ?
                new ObjectParameter("decTo", decTo) :
                new ObjectParameter("decTo", typeof(string));
    
            var keywordsParameter = keywords != null ?
                new ObjectParameter("keywords", keywords) :
                new ObjectParameter("keywords", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGuestBook_SearchReturns", searchStrParameter, firstNameParameter, lastNameParameter, submitterNameParameter, decFromParameter, decToParameter, keywordsParameter, approvedParameter);
        }
    
        public virtual ObjectResult<spGuestBook_SelectOneRecord_Result> spGuestBook_SelectOneRecord(Nullable<int> guestBookID)
        {
            var guestBookIDParameter = guestBookID.HasValue ?
                new ObjectParameter("GuestBookID", guestBookID) :
                new ObjectParameter("GuestBookID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGuestBook_SelectOneRecord_Result>("spGuestBook_SelectOneRecord", guestBookIDParameter);
        }
    
        public virtual ObjectResult<spGuestBook_SelectRecord_Result> spGuestBook_SelectRecord(Nullable<int> obituaryID)
        {
            var obituaryIDParameter = obituaryID.HasValue ?
                new ObjectParameter("ObituaryID", obituaryID) :
                new ObjectParameter("ObituaryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGuestBook_SelectRecord_Result>("spGuestBook_SelectRecord", obituaryIDParameter);
        }
    
        public virtual ObjectResult<spGuestBook_SelectRecord_top4_Result> spGuestBook_SelectRecord_top4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGuestBook_SelectRecord_top4_Result>("spGuestBook_SelectRecord_top4");
        }
    
        public virtual ObjectResult<spGuestBook_SelectRecordApp_Result> spGuestBook_SelectRecordApp(Nullable<int> obituaryID, string approved)
        {
            var obituaryIDParameter = obituaryID.HasValue ?
                new ObjectParameter("ObituaryID", obituaryID) :
                new ObjectParameter("ObituaryID", typeof(int));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGuestBook_SelectRecordApp_Result>("spGuestBook_SelectRecordApp", obituaryIDParameter, approvedParameter);
        }
    
        public virtual int spGuestBook_UpdAllRecords(string guestBookIDList, string approver, string approved, Nullable<System.DateTime> approvalDate, string signedByDBTeam4EAA, ObjectParameter returnValue)
        {
            var guestBookIDListParameter = guestBookIDList != null ?
                new ObjectParameter("GuestBookIDList", guestBookIDList) :
                new ObjectParameter("GuestBookIDList", typeof(string));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGuestBook_UpdAllRecords", guestBookIDListParameter, approverParameter, approvedParameter, approvalDateParameter, signedByDBTeam4EAAParameter, returnValue);
        }
    
        public virtual int spGuestBook_UpdRecord(Nullable<int> guestBookID, Nullable<System.DateTime> dateSubmitted, string submitterName, string submitterMemberNum, string submitterComments, string approver, string approved, Nullable<System.DateTime> approvalDate, string approverComments, string signedByDBTeam4EAA, ObjectParameter returnValue)
        {
            var guestBookIDParameter = guestBookID.HasValue ?
                new ObjectParameter("GuestBookID", guestBookID) :
                new ObjectParameter("GuestBookID", typeof(int));
    
            var dateSubmittedParameter = dateSubmitted.HasValue ?
                new ObjectParameter("DateSubmitted", dateSubmitted) :
                new ObjectParameter("DateSubmitted", typeof(System.DateTime));
    
            var submitterNameParameter = submitterName != null ?
                new ObjectParameter("SubmitterName", submitterName) :
                new ObjectParameter("SubmitterName", typeof(string));
    
            var submitterMemberNumParameter = submitterMemberNum != null ?
                new ObjectParameter("SubmitterMemberNum", submitterMemberNum) :
                new ObjectParameter("SubmitterMemberNum", typeof(string));
    
            var submitterCommentsParameter = submitterComments != null ?
                new ObjectParameter("SubmitterComments", submitterComments) :
                new ObjectParameter("SubmitterComments", typeof(string));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var approverCommentsParameter = approverComments != null ?
                new ObjectParameter("ApproverComments", approverComments) :
                new ObjectParameter("ApproverComments", typeof(string));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGuestBook_UpdRecord", guestBookIDParameter, dateSubmittedParameter, submitterNameParameter, submitterMemberNumParameter, submitterCommentsParameter, approverParameter, approvedParameter, approvalDateParameter, approverCommentsParameter, signedByDBTeam4EAAParameter, returnValue);
        }
    
        public virtual int spGuestBook_UpdRecordShort(Nullable<int> guestBookID, Nullable<System.DateTime> dateSubmitted, string submitterName, string submitterMemberNum, string submitterComments, string approved, string approverComments, string signedByDBTeam4EAA, ObjectParameter returnValue)
        {
            var guestBookIDParameter = guestBookID.HasValue ?
                new ObjectParameter("GuestBookID", guestBookID) :
                new ObjectParameter("GuestBookID", typeof(int));
    
            var dateSubmittedParameter = dateSubmitted.HasValue ?
                new ObjectParameter("DateSubmitted", dateSubmitted) :
                new ObjectParameter("DateSubmitted", typeof(System.DateTime));
    
            var submitterNameParameter = submitterName != null ?
                new ObjectParameter("SubmitterName", submitterName) :
                new ObjectParameter("SubmitterName", typeof(string));
    
            var submitterMemberNumParameter = submitterMemberNum != null ?
                new ObjectParameter("SubmitterMemberNum", submitterMemberNum) :
                new ObjectParameter("SubmitterMemberNum", typeof(string));
    
            var submitterCommentsParameter = submitterComments != null ?
                new ObjectParameter("SubmitterComments", submitterComments) :
                new ObjectParameter("SubmitterComments", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approverCommentsParameter = approverComments != null ?
                new ObjectParameter("ApproverComments", approverComments) :
                new ObjectParameter("ApproverComments", typeof(string));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGuestBook_UpdRecordShort", guestBookIDParameter, dateSubmittedParameter, submitterNameParameter, submitterMemberNumParameter, submitterCommentsParameter, approvedParameter, approverCommentsParameter, signedByDBTeam4EAAParameter, returnValue);
        }
    
        public virtual int spObituaries_DeleteRecord(Nullable<int> obitKeyID)
        {
            var obitKeyIDParameter = obitKeyID.HasValue ?
                new ObjectParameter("ObitKeyID", obitKeyID) :
                new ObjectParameter("ObitKeyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spObituaries_DeleteRecord", obitKeyIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spObituaries_NewRecord(string decHonorific, string decFirstName, string decLastName, string decAddress, string decAddress2, string decCity, string decState, string decZip, string decMemberNum, Nullable<System.DateTime> decDateDeath, Nullable<System.DateTime> decDateBirth, string obituary, string photo, string contactFirstName, string contactLastName, string contactAddress, string contactAddress2, string contactCity, string contactState, string contactZip, string contactMemberNum, string contactPhoneNum, string contactEmail, Nullable<System.DateTime> dateSubmitted, string approver, string approved, Nullable<System.DateTime> approvalDate, string approverComments, string risk, string spotLight, Nullable<int> memorialWallYear, string engrave, string engrave2, string dateBirthFormat, string dateDeathFormat, string signedByDBTeam4EAA, Nullable<System.Guid> photoID, ObjectParameter retrunValue)
        {
            var decHonorificParameter = decHonorific != null ?
                new ObjectParameter("DecHonorific", decHonorific) :
                new ObjectParameter("DecHonorific", typeof(string));
    
            var decFirstNameParameter = decFirstName != null ?
                new ObjectParameter("DecFirstName", decFirstName) :
                new ObjectParameter("DecFirstName", typeof(string));
    
            var decLastNameParameter = decLastName != null ?
                new ObjectParameter("DecLastName", decLastName) :
                new ObjectParameter("DecLastName", typeof(string));
    
            var decAddressParameter = decAddress != null ?
                new ObjectParameter("DecAddress", decAddress) :
                new ObjectParameter("DecAddress", typeof(string));
    
            var decAddress2Parameter = decAddress2 != null ?
                new ObjectParameter("DecAddress2", decAddress2) :
                new ObjectParameter("DecAddress2", typeof(string));
    
            var decCityParameter = decCity != null ?
                new ObjectParameter("DecCity", decCity) :
                new ObjectParameter("DecCity", typeof(string));
    
            var decStateParameter = decState != null ?
                new ObjectParameter("DecState", decState) :
                new ObjectParameter("DecState", typeof(string));
    
            var decZipParameter = decZip != null ?
                new ObjectParameter("DecZip", decZip) :
                new ObjectParameter("DecZip", typeof(string));
    
            var decMemberNumParameter = decMemberNum != null ?
                new ObjectParameter("DecMemberNum", decMemberNum) :
                new ObjectParameter("DecMemberNum", typeof(string));
    
            var decDateDeathParameter = decDateDeath.HasValue ?
                new ObjectParameter("DecDateDeath", decDateDeath) :
                new ObjectParameter("DecDateDeath", typeof(System.DateTime));
    
            var decDateBirthParameter = decDateBirth.HasValue ?
                new ObjectParameter("DecDateBirth", decDateBirth) :
                new ObjectParameter("DecDateBirth", typeof(System.DateTime));
    
            var obituaryParameter = obituary != null ?
                new ObjectParameter("Obituary", obituary) :
                new ObjectParameter("Obituary", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("Photo", photo) :
                new ObjectParameter("Photo", typeof(string));
    
            var contactFirstNameParameter = contactFirstName != null ?
                new ObjectParameter("ContactFirstName", contactFirstName) :
                new ObjectParameter("ContactFirstName", typeof(string));
    
            var contactLastNameParameter = contactLastName != null ?
                new ObjectParameter("ContactLastName", contactLastName) :
                new ObjectParameter("ContactLastName", typeof(string));
    
            var contactAddressParameter = contactAddress != null ?
                new ObjectParameter("ContactAddress", contactAddress) :
                new ObjectParameter("ContactAddress", typeof(string));
    
            var contactAddress2Parameter = contactAddress2 != null ?
                new ObjectParameter("ContactAddress2", contactAddress2) :
                new ObjectParameter("ContactAddress2", typeof(string));
    
            var contactCityParameter = contactCity != null ?
                new ObjectParameter("ContactCity", contactCity) :
                new ObjectParameter("ContactCity", typeof(string));
    
            var contactStateParameter = contactState != null ?
                new ObjectParameter("ContactState", contactState) :
                new ObjectParameter("ContactState", typeof(string));
    
            var contactZipParameter = contactZip != null ?
                new ObjectParameter("ContactZip", contactZip) :
                new ObjectParameter("ContactZip", typeof(string));
    
            var contactMemberNumParameter = contactMemberNum != null ?
                new ObjectParameter("ContactMemberNum", contactMemberNum) :
                new ObjectParameter("ContactMemberNum", typeof(string));
    
            var contactPhoneNumParameter = contactPhoneNum != null ?
                new ObjectParameter("ContactPhoneNum", contactPhoneNum) :
                new ObjectParameter("ContactPhoneNum", typeof(string));
    
            var contactEmailParameter = contactEmail != null ?
                new ObjectParameter("ContactEmail", contactEmail) :
                new ObjectParameter("ContactEmail", typeof(string));
    
            var dateSubmittedParameter = dateSubmitted.HasValue ?
                new ObjectParameter("DateSubmitted", dateSubmitted) :
                new ObjectParameter("DateSubmitted", typeof(System.DateTime));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var approverCommentsParameter = approverComments != null ?
                new ObjectParameter("ApproverComments", approverComments) :
                new ObjectParameter("ApproverComments", typeof(string));
    
            var riskParameter = risk != null ?
                new ObjectParameter("Risk", risk) :
                new ObjectParameter("Risk", typeof(string));
    
            var spotLightParameter = spotLight != null ?
                new ObjectParameter("SpotLight", spotLight) :
                new ObjectParameter("SpotLight", typeof(string));
    
            var memorialWallYearParameter = memorialWallYear.HasValue ?
                new ObjectParameter("MemorialWallYear", memorialWallYear) :
                new ObjectParameter("MemorialWallYear", typeof(int));
    
            var engraveParameter = engrave != null ?
                new ObjectParameter("Engrave", engrave) :
                new ObjectParameter("Engrave", typeof(string));
    
            var engrave2Parameter = engrave2 != null ?
                new ObjectParameter("Engrave2", engrave2) :
                new ObjectParameter("Engrave2", typeof(string));
    
            var dateBirthFormatParameter = dateBirthFormat != null ?
                new ObjectParameter("DateBirthFormat", dateBirthFormat) :
                new ObjectParameter("DateBirthFormat", typeof(string));
    
            var dateDeathFormatParameter = dateDeathFormat != null ?
                new ObjectParameter("DateDeathFormat", dateDeathFormat) :
                new ObjectParameter("DateDeathFormat", typeof(string));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            var photoIDParameter = photoID.HasValue ?
                new ObjectParameter("PhotoID", photoID) :
                new ObjectParameter("PhotoID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spObituaries_NewRecord", decHonorificParameter, decFirstNameParameter, decLastNameParameter, decAddressParameter, decAddress2Parameter, decCityParameter, decStateParameter, decZipParameter, decMemberNumParameter, decDateDeathParameter, decDateBirthParameter, obituaryParameter, photoParameter, contactFirstNameParameter, contactLastNameParameter, contactAddressParameter, contactAddress2Parameter, contactCityParameter, contactStateParameter, contactZipParameter, contactMemberNumParameter, contactPhoneNumParameter, contactEmailParameter, dateSubmittedParameter, approverParameter, approvedParameter, approvalDateParameter, approverCommentsParameter, riskParameter, spotLightParameter, memorialWallYearParameter, engraveParameter, engrave2Parameter, dateBirthFormatParameter, dateDeathFormatParameter, signedByDBTeam4EAAParameter, photoIDParameter, retrunValue);
        }
    
        public virtual int spObituaries_SearchReturns(string searchStr, string firstName, string lastName, string approved, string decFrom, string decTo, string decInduct, string keywords, string sortOrder)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var decFromParameter = decFrom != null ?
                new ObjectParameter("decFrom", decFrom) :
                new ObjectParameter("decFrom", typeof(string));
    
            var decToParameter = decTo != null ?
                new ObjectParameter("decTo", decTo) :
                new ObjectParameter("decTo", typeof(string));
    
            var decInductParameter = decInduct != null ?
                new ObjectParameter("decInduct", decInduct) :
                new ObjectParameter("decInduct", typeof(string));
    
            var keywordsParameter = keywords != null ?
                new ObjectParameter("keywords", keywords) :
                new ObjectParameter("keywords", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("sortOrder", sortOrder) :
                new ObjectParameter("sortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spObituaries_SearchReturns", searchStrParameter, firstNameParameter, lastNameParameter, approvedParameter, decFromParameter, decToParameter, decInductParameter, keywordsParameter, sortOrderParameter);
        }
    
        public virtual ObjectResult<spObituaries_SelectRecord_Result> spObituaries_SelectRecord(Nullable<int> obitKeyID)
        {
            var obitKeyIDParameter = obitKeyID.HasValue ?
                new ObjectParameter("ObitKeyID", obitKeyID) :
                new ObjectParameter("ObitKeyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituaries_SelectRecord_Result>("spObituaries_SelectRecord", obitKeyIDParameter);
        }
    
        public virtual ObjectResult<spObituaries_SelectRecord_Top2_Result> spObituaries_SelectRecord_Top2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituaries_SelectRecord_Top2_Result>("spObituaries_SelectRecord_Top2");
        }
    
        public virtual ObjectResult<spObituaries_SelectRecord_Top4_Result> spObituaries_SelectRecord_Top4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituaries_SelectRecord_Top4_Result>("spObituaries_SelectRecord_Top4");
        }
    
        public virtual ObjectResult<string> spObituaries_SelectRecord_Unapproved()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spObituaries_SelectRecord_Unapproved");
        }
    
        public virtual ObjectResult<spObituaries_SelectRecordApp_Result> spObituaries_SelectRecordApp(Nullable<int> obitKeyID, string approved)
        {
            var obitKeyIDParameter = obitKeyID.HasValue ?
                new ObjectParameter("ObitKeyID", obitKeyID) :
                new ObjectParameter("ObitKeyID", typeof(int));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituaries_SelectRecordApp_Result>("spObituaries_SelectRecordApp", obitKeyIDParameter, approvedParameter);
        }
    
        public virtual ObjectResult<spObituaries_SelectRecordApprover_Result> spObituaries_SelectRecordApprover(string approver)
        {
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituaries_SelectRecordApprover_Result>("spObituaries_SelectRecordApprover", approverParameter);
        }
    
        public virtual ObjectResult<spObituaries_SelectWallRecord_Result> spObituaries_SelectWallRecord(Nullable<int> obitKeyID)
        {
            var obitKeyIDParameter = obitKeyID.HasValue ?
                new ObjectParameter("ObitKeyID", obitKeyID) :
                new ObjectParameter("ObitKeyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituaries_SelectWallRecord_Result>("spObituaries_SelectWallRecord", obitKeyIDParameter);
        }
    
        public virtual int spObituaries_UpdRecord(Nullable<int> obitKeyID, string decHonorific, string decFirstName, string decLastName, string decAddress, string decAddress2, string decCity, string decState, string decZip, string decMemberNum, Nullable<System.DateTime> decDateDeath, Nullable<System.DateTime> decDateBirth, string obituary, string photo, string contactFirstName, string contactLastName, string contactAddress, string contactAddress2, string contactCity, string contactState, string contactZip, string contactMemberNum, string contactPhoneNum, string contactEmail, Nullable<System.DateTime> dateSubmitted, string approver, string approved, Nullable<System.DateTime> approvalDate, string approverComments, string risk, string spotLight, Nullable<int> memorialWallYear, string engrave, string engrave2, string dateBirthFormat, string dateDeathFormat, string signedByDBTeam4EAA, Nullable<System.Guid> photoID, ObjectParameter returnValue)
        {
            var obitKeyIDParameter = obitKeyID.HasValue ?
                new ObjectParameter("ObitKeyID", obitKeyID) :
                new ObjectParameter("ObitKeyID", typeof(int));
    
            var decHonorificParameter = decHonorific != null ?
                new ObjectParameter("DecHonorific", decHonorific) :
                new ObjectParameter("DecHonorific", typeof(string));
    
            var decFirstNameParameter = decFirstName != null ?
                new ObjectParameter("DecFirstName", decFirstName) :
                new ObjectParameter("DecFirstName", typeof(string));
    
            var decLastNameParameter = decLastName != null ?
                new ObjectParameter("DecLastName", decLastName) :
                new ObjectParameter("DecLastName", typeof(string));
    
            var decAddressParameter = decAddress != null ?
                new ObjectParameter("DecAddress", decAddress) :
                new ObjectParameter("DecAddress", typeof(string));
    
            var decAddress2Parameter = decAddress2 != null ?
                new ObjectParameter("DecAddress2", decAddress2) :
                new ObjectParameter("DecAddress2", typeof(string));
    
            var decCityParameter = decCity != null ?
                new ObjectParameter("DecCity", decCity) :
                new ObjectParameter("DecCity", typeof(string));
    
            var decStateParameter = decState != null ?
                new ObjectParameter("DecState", decState) :
                new ObjectParameter("DecState", typeof(string));
    
            var decZipParameter = decZip != null ?
                new ObjectParameter("DecZip", decZip) :
                new ObjectParameter("DecZip", typeof(string));
    
            var decMemberNumParameter = decMemberNum != null ?
                new ObjectParameter("DecMemberNum", decMemberNum) :
                new ObjectParameter("DecMemberNum", typeof(string));
    
            var decDateDeathParameter = decDateDeath.HasValue ?
                new ObjectParameter("DecDateDeath", decDateDeath) :
                new ObjectParameter("DecDateDeath", typeof(System.DateTime));
    
            var decDateBirthParameter = decDateBirth.HasValue ?
                new ObjectParameter("DecDateBirth", decDateBirth) :
                new ObjectParameter("DecDateBirth", typeof(System.DateTime));
    
            var obituaryParameter = obituary != null ?
                new ObjectParameter("Obituary", obituary) :
                new ObjectParameter("Obituary", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("Photo", photo) :
                new ObjectParameter("Photo", typeof(string));
    
            var contactFirstNameParameter = contactFirstName != null ?
                new ObjectParameter("ContactFirstName", contactFirstName) :
                new ObjectParameter("ContactFirstName", typeof(string));
    
            var contactLastNameParameter = contactLastName != null ?
                new ObjectParameter("ContactLastName", contactLastName) :
                new ObjectParameter("ContactLastName", typeof(string));
    
            var contactAddressParameter = contactAddress != null ?
                new ObjectParameter("ContactAddress", contactAddress) :
                new ObjectParameter("ContactAddress", typeof(string));
    
            var contactAddress2Parameter = contactAddress2 != null ?
                new ObjectParameter("ContactAddress2", contactAddress2) :
                new ObjectParameter("ContactAddress2", typeof(string));
    
            var contactCityParameter = contactCity != null ?
                new ObjectParameter("ContactCity", contactCity) :
                new ObjectParameter("ContactCity", typeof(string));
    
            var contactStateParameter = contactState != null ?
                new ObjectParameter("ContactState", contactState) :
                new ObjectParameter("ContactState", typeof(string));
    
            var contactZipParameter = contactZip != null ?
                new ObjectParameter("ContactZip", contactZip) :
                new ObjectParameter("ContactZip", typeof(string));
    
            var contactMemberNumParameter = contactMemberNum != null ?
                new ObjectParameter("ContactMemberNum", contactMemberNum) :
                new ObjectParameter("ContactMemberNum", typeof(string));
    
            var contactPhoneNumParameter = contactPhoneNum != null ?
                new ObjectParameter("ContactPhoneNum", contactPhoneNum) :
                new ObjectParameter("ContactPhoneNum", typeof(string));
    
            var contactEmailParameter = contactEmail != null ?
                new ObjectParameter("ContactEmail", contactEmail) :
                new ObjectParameter("ContactEmail", typeof(string));
    
            var dateSubmittedParameter = dateSubmitted.HasValue ?
                new ObjectParameter("DateSubmitted", dateSubmitted) :
                new ObjectParameter("DateSubmitted", typeof(System.DateTime));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var approverCommentsParameter = approverComments != null ?
                new ObjectParameter("ApproverComments", approverComments) :
                new ObjectParameter("ApproverComments", typeof(string));
    
            var riskParameter = risk != null ?
                new ObjectParameter("Risk", risk) :
                new ObjectParameter("Risk", typeof(string));
    
            var spotLightParameter = spotLight != null ?
                new ObjectParameter("SpotLight", spotLight) :
                new ObjectParameter("SpotLight", typeof(string));
    
            var memorialWallYearParameter = memorialWallYear.HasValue ?
                new ObjectParameter("MemorialWallYear", memorialWallYear) :
                new ObjectParameter("MemorialWallYear", typeof(int));
    
            var engraveParameter = engrave != null ?
                new ObjectParameter("Engrave", engrave) :
                new ObjectParameter("Engrave", typeof(string));
    
            var engrave2Parameter = engrave2 != null ?
                new ObjectParameter("Engrave2", engrave2) :
                new ObjectParameter("Engrave2", typeof(string));
    
            var dateBirthFormatParameter = dateBirthFormat != null ?
                new ObjectParameter("DateBirthFormat", dateBirthFormat) :
                new ObjectParameter("DateBirthFormat", typeof(string));
    
            var dateDeathFormatParameter = dateDeathFormat != null ?
                new ObjectParameter("DateDeathFormat", dateDeathFormat) :
                new ObjectParameter("DateDeathFormat", typeof(string));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            var photoIDParameter = photoID.HasValue ?
                new ObjectParameter("PhotoID", photoID) :
                new ObjectParameter("PhotoID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spObituaries_UpdRecord", obitKeyIDParameter, decHonorificParameter, decFirstNameParameter, decLastNameParameter, decAddressParameter, decAddress2Parameter, decCityParameter, decStateParameter, decZipParameter, decMemberNumParameter, decDateDeathParameter, decDateBirthParameter, obituaryParameter, photoParameter, contactFirstNameParameter, contactLastNameParameter, contactAddressParameter, contactAddress2Parameter, contactCityParameter, contactStateParameter, contactZipParameter, contactMemberNumParameter, contactPhoneNumParameter, contactEmailParameter, dateSubmittedParameter, approverParameter, approvedParameter, approvalDateParameter, approverCommentsParameter, riskParameter, spotLightParameter, memorialWallYearParameter, engraveParameter, engrave2Parameter, dateBirthFormatParameter, dateDeathFormatParameter, signedByDBTeam4EAAParameter, photoIDParameter, returnValue);
        }
    
        public virtual int spObituaries_UpdRecordAppr(Nullable<int> obitKeyID, string approver, string approved, Nullable<System.DateTime> approvalDate, string signedByDBTeam4EAA, ObjectParameter returnValue)
        {
            var obitKeyIDParameter = obitKeyID.HasValue ?
                new ObjectParameter("ObitKeyID", obitKeyID) :
                new ObjectParameter("ObitKeyID", typeof(int));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spObituaries_UpdRecordAppr", obitKeyIDParameter, approverParameter, approvedParameter, approvalDateParameter, signedByDBTeam4EAAParameter, returnValue);
        }
    
        public virtual ObjectResult<spObituariesGuesBook_SelectApp_Result> spObituariesGuesBook_SelectApp(string approver)
        {
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObituariesGuesBook_SelectApp_Result>("spObituariesGuesBook_SelectApp", approverParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spObituariesMemorialWall_NewRecord(string decHonorific, string decFirstName, string decLastName, string decAddress, string decAddress2, string decCity, string decState, string decZip, string decMemberNum, Nullable<System.DateTime> decDateDeath, Nullable<System.DateTime> decDateBirth, string obituary, string photo, string contactFirstName, string contactLastName, string contactAddress, string contactAddress2, string contactCity, string contactState, string contactZip, string contactMemberNum, string contactPhoneNum, string contactEmail, Nullable<System.DateTime> dateSubmitted, string approver, string approved, Nullable<System.DateTime> approvalDate, string approverComments, string risk, string spotLight, Nullable<int> memorialWallYear, string engrave, string engrave2, string dateBirthFormat, string dateDeathFormat, string signedByDBTeam4EAA, Nullable<System.Guid> photoID, ObjectParameter retrunValue)
        {
            var decHonorificParameter = decHonorific != null ?
                new ObjectParameter("DecHonorific", decHonorific) :
                new ObjectParameter("DecHonorific", typeof(string));
    
            var decFirstNameParameter = decFirstName != null ?
                new ObjectParameter("DecFirstName", decFirstName) :
                new ObjectParameter("DecFirstName", typeof(string));
    
            var decLastNameParameter = decLastName != null ?
                new ObjectParameter("DecLastName", decLastName) :
                new ObjectParameter("DecLastName", typeof(string));
    
            var decAddressParameter = decAddress != null ?
                new ObjectParameter("DecAddress", decAddress) :
                new ObjectParameter("DecAddress", typeof(string));
    
            var decAddress2Parameter = decAddress2 != null ?
                new ObjectParameter("DecAddress2", decAddress2) :
                new ObjectParameter("DecAddress2", typeof(string));
    
            var decCityParameter = decCity != null ?
                new ObjectParameter("DecCity", decCity) :
                new ObjectParameter("DecCity", typeof(string));
    
            var decStateParameter = decState != null ?
                new ObjectParameter("DecState", decState) :
                new ObjectParameter("DecState", typeof(string));
    
            var decZipParameter = decZip != null ?
                new ObjectParameter("DecZip", decZip) :
                new ObjectParameter("DecZip", typeof(string));
    
            var decMemberNumParameter = decMemberNum != null ?
                new ObjectParameter("DecMemberNum", decMemberNum) :
                new ObjectParameter("DecMemberNum", typeof(string));
    
            var decDateDeathParameter = decDateDeath.HasValue ?
                new ObjectParameter("DecDateDeath", decDateDeath) :
                new ObjectParameter("DecDateDeath", typeof(System.DateTime));
    
            var decDateBirthParameter = decDateBirth.HasValue ?
                new ObjectParameter("DecDateBirth", decDateBirth) :
                new ObjectParameter("DecDateBirth", typeof(System.DateTime));
    
            var obituaryParameter = obituary != null ?
                new ObjectParameter("Obituary", obituary) :
                new ObjectParameter("Obituary", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("Photo", photo) :
                new ObjectParameter("Photo", typeof(string));
    
            var contactFirstNameParameter = contactFirstName != null ?
                new ObjectParameter("ContactFirstName", contactFirstName) :
                new ObjectParameter("ContactFirstName", typeof(string));
    
            var contactLastNameParameter = contactLastName != null ?
                new ObjectParameter("ContactLastName", contactLastName) :
                new ObjectParameter("ContactLastName", typeof(string));
    
            var contactAddressParameter = contactAddress != null ?
                new ObjectParameter("ContactAddress", contactAddress) :
                new ObjectParameter("ContactAddress", typeof(string));
    
            var contactAddress2Parameter = contactAddress2 != null ?
                new ObjectParameter("ContactAddress2", contactAddress2) :
                new ObjectParameter("ContactAddress2", typeof(string));
    
            var contactCityParameter = contactCity != null ?
                new ObjectParameter("ContactCity", contactCity) :
                new ObjectParameter("ContactCity", typeof(string));
    
            var contactStateParameter = contactState != null ?
                new ObjectParameter("ContactState", contactState) :
                new ObjectParameter("ContactState", typeof(string));
    
            var contactZipParameter = contactZip != null ?
                new ObjectParameter("ContactZip", contactZip) :
                new ObjectParameter("ContactZip", typeof(string));
    
            var contactMemberNumParameter = contactMemberNum != null ?
                new ObjectParameter("ContactMemberNum", contactMemberNum) :
                new ObjectParameter("ContactMemberNum", typeof(string));
    
            var contactPhoneNumParameter = contactPhoneNum != null ?
                new ObjectParameter("ContactPhoneNum", contactPhoneNum) :
                new ObjectParameter("ContactPhoneNum", typeof(string));
    
            var contactEmailParameter = contactEmail != null ?
                new ObjectParameter("ContactEmail", contactEmail) :
                new ObjectParameter("ContactEmail", typeof(string));
    
            var dateSubmittedParameter = dateSubmitted.HasValue ?
                new ObjectParameter("DateSubmitted", dateSubmitted) :
                new ObjectParameter("DateSubmitted", typeof(System.DateTime));
    
            var approverParameter = approver != null ?
                new ObjectParameter("Approver", approver) :
                new ObjectParameter("Approver", typeof(string));
    
            var approvedParameter = approved != null ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(string));
    
            var approvalDateParameter = approvalDate.HasValue ?
                new ObjectParameter("ApprovalDate", approvalDate) :
                new ObjectParameter("ApprovalDate", typeof(System.DateTime));
    
            var approverCommentsParameter = approverComments != null ?
                new ObjectParameter("ApproverComments", approverComments) :
                new ObjectParameter("ApproverComments", typeof(string));
    
            var riskParameter = risk != null ?
                new ObjectParameter("Risk", risk) :
                new ObjectParameter("Risk", typeof(string));
    
            var spotLightParameter = spotLight != null ?
                new ObjectParameter("SpotLight", spotLight) :
                new ObjectParameter("SpotLight", typeof(string));
    
            var memorialWallYearParameter = memorialWallYear.HasValue ?
                new ObjectParameter("MemorialWallYear", memorialWallYear) :
                new ObjectParameter("MemorialWallYear", typeof(int));
    
            var engraveParameter = engrave != null ?
                new ObjectParameter("Engrave", engrave) :
                new ObjectParameter("Engrave", typeof(string));
    
            var engrave2Parameter = engrave2 != null ?
                new ObjectParameter("Engrave2", engrave2) :
                new ObjectParameter("Engrave2", typeof(string));
    
            var dateBirthFormatParameter = dateBirthFormat != null ?
                new ObjectParameter("DateBirthFormat", dateBirthFormat) :
                new ObjectParameter("DateBirthFormat", typeof(string));
    
            var dateDeathFormatParameter = dateDeathFormat != null ?
                new ObjectParameter("DateDeathFormat", dateDeathFormat) :
                new ObjectParameter("DateDeathFormat", typeof(string));
    
            var signedByDBTeam4EAAParameter = signedByDBTeam4EAA != null ?
                new ObjectParameter("SignedByDBTeam4EAA", signedByDBTeam4EAA) :
                new ObjectParameter("SignedByDBTeam4EAA", typeof(string));
    
            var photoIDParameter = photoID.HasValue ?
                new ObjectParameter("PhotoID", photoID) :
                new ObjectParameter("PhotoID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spObituariesMemorialWall_NewRecord", decHonorificParameter, decFirstNameParameter, decLastNameParameter, decAddressParameter, decAddress2Parameter, decCityParameter, decStateParameter, decZipParameter, decMemberNumParameter, decDateDeathParameter, decDateBirthParameter, obituaryParameter, photoParameter, contactFirstNameParameter, contactLastNameParameter, contactAddressParameter, contactAddress2Parameter, contactCityParameter, contactStateParameter, contactZipParameter, contactMemberNumParameter, contactPhoneNumParameter, contactEmailParameter, dateSubmittedParameter, approverParameter, approvedParameter, approvalDateParameter, approverCommentsParameter, riskParameter, spotLightParameter, memorialWallYearParameter, engraveParameter, engrave2Parameter, dateBirthFormatParameter, dateDeathFormatParameter, signedByDBTeam4EAAParameter, photoIDParameter, retrunValue);
        }
    }
}
